"""
Test SLSTR L1 Product data from testing
"""
from datetime import datetime as dt

SLSTRL1_test_path = r"D:\Sentinel-3\SLSTR\S3A_SL_1_RBT____20180614T192802_20180614T193102_20180614T215609_0180_032_199_0900_SVL_O_NR_003.SEN3\xfdumanifest.xml"

SLSTRL1_type_string = "SL_1_RBT"
SLSTRL1_display_name_500m = "S3A_SL_1_RBT____20180614T192802_20180614T193102_20180614T215609_0180_032_199_0900_SVL_O_NR_003.SEN3_500m"
SLSTRL1_display_name_1km = "S3A_SL_1_RBT____20180614T192802_20180614T193102_20180614T215609_0180_032_199_0900_SVL_O_NR_003.SEN3_1km"

SLSTRL1_test_attributes = {"product_string": "SL_1_RBT",
                           # "product_columns": 4865,
                           # "product_rows": 4091,
                           "start_time": dt(2018, 06, 14, 19, 28, 2, 229347),
                           "end_time": dt(2018, 06, 14, 19, 31, 02, 229347),
                           #"spatial_sampling_al": 294.0,
                           #"spatial_sampling_ac": 270.0,
                           "platform": "Sentinel-3A",
                           "instrument": "SLSTR",
                           "band_names": ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "F1", "F2"],
                           "band_central_wavelengths": [554.27, 659.47, 868, 1374.8, 1613.4, 2255.7, 3742, 10854, 12022.5, 3742, 10854],
                           "band_widths": [19.26, 19.25, 20.6, 20.8, 60.68, 50.15, 398, 776, 905, 398, 776],
                           #"invalid_pixels_percentage": 0.0,
                           #"cosmetic_pixels_percentage": 3.0,
                           #"duplicated_pixels_percentage": 0.0,
                           #"saturated_pixels_percentage": 0.0,
                           #"dubious_pixels_percentage": 0.0,
                           #"saline_water_pixels_percentage": 53.0,
                           #"coastal_pixels_percentage": 1.0,
                           #"fresh_inland_water_pixels_percentage": 2.0,
                           #"tidal_region_pixels_percentage": 5.0,
                           #"bright_pixels_percentage": 50.619987
                           }

expected_mask_variable_names_1km = ['F1_exception_in_ISP_absent', 'F1_exception_in_pixel_absent',
                                    'F1_exception_in_not_decompressed', 'F1_exception_in_no_signal',
                                    'F1_exception_in_saturation', 'F1_exception_in_invalid_radiance',
                                    'F1_exception_in_no_parameters', 'F1_exception_in_unfilled_pixel',
                                    'F1_exception_io_ISP_absent', 'F1_exception_io_pixel_absent',
                                    'F1_exception_io_not_decompressed', 'F1_exception_io_no_signal',
                                    'F1_exception_io_saturation', 'F1_exception_io_invalid_radiance',
                                    'F1_exception_io_no_parameters', 'F1_exception_io_unfilled_pixel',
                                    'F2_exception_in_ISP_absent', 'F2_exception_in_pixel_absent',
                                    'F2_exception_in_not_decompressed', 'F2_exception_in_no_signal',
                                    'F2_exception_in_saturation', 'F2_exception_in_invalid_radiance',
                                    'F2_exception_in_no_parameters', 'F2_exception_in_unfilled_pixel',
                                    'F2_exception_io_ISP_absent', 'F2_exception_io_pixel_absent',
                                    'F2_exception_io_not_decompressed', 'F2_exception_io_no_signal',
                                    'F2_exception_io_saturation', 'F2_exception_io_invalid_radiance',
                                    'F2_exception_io_no_parameters', 'F2_exception_io_unfilled_pixel',
                                    'bayes_in_single_low', 'bayes_in_single_moderate', 'bayes_in_dual_low',
                                    'bayes_in_dual_moderate', 'cloud_in_visible', 'cloud_in_1_37_threshold',
                                    'cloud_in_1_6_small_histogram', 'cloud_in_1_6_large_histogram',
                                    'cloud_in_2_25_small_histogram', 'cloud_in_2_25_large_histogram',
                                    'cloud_in_11_spatial_coherence', 'cloud_in_gross_cloud', 'cloud_in_thin_cirrus',
                                    'cloud_in_medium_high', 'cloud_in_fog_low_stratus',
                                    'cloud_in_11_12_view_difference', 'cloud_in_3_7_11_view_difference',
                                    'cloud_in_thermal_histogram', 'confidence_in_coastline', 'confidence_in_ocean',
                                    'confidence_in_tidal', 'confidence_in_land', 'confidence_in_inland_water',
                                    'confidence_in_unfilled', 'confidence_in_cosmetic', 'confidence_in_duplicate',
                                    'confidence_in_day', 'confidence_in_twilight', 'confidence_in_sun_glint',
                                    'confidence_in_snow', 'confidence_in_summary_cloud',
                                    'confidence_in_summary_pointing', 'pointing_in_FlipMirrorAbsoluteError',
                                    'pointing_in_FlipMirrorIntegratedError', 'pointing_in_FlipMirrorRMSError',
                                    'pointing_in_ScanMirrorAbsoluteError', 'pointing_in_ScanMirrorIntegratedError',
                                    'pointing_in_ScanMirrorRMSError', 'pointing_in_ScanTimeError',
                                    'pointing_in_Platform_Mode', 'bayes_io_single_low', 'bayes_io_single_moderate',
                                    'bayes_io_dual_low', 'bayes_io_dual_moderate', 'cloud_io_visible',
                                    'cloud_io_1_37_threshold', 'cloud_io_1_6_small_histogram',
                                    'cloud_io_1_6_large_histogram', 'cloud_io_2_25_small_histogram',
                                    'cloud_io_2_25_large_histogram', 'cloud_io_11_spatial_coherence',
                                    'cloud_io_gross_cloud', 'cloud_io_thin_cirrus', 'cloud_io_medium_high',
                                    'cloud_io_fog_low_stratus', 'cloud_io_11_12_view_difference',
                                    'cloud_io_3_7_11_view_difference', 'cloud_io_thermal_histogram',
                                    'confidence_io_coastline', 'confidence_io_ocean', 'confidence_io_tidal',
                                    'confidence_io_land', 'confidence_io_inland_water', 'confidence_io_unfilled',
                                    'confidence_io_cosmetic', 'confidence_io_duplicate', 'confidence_io_day',
                                    'confidence_io_twilight', 'confidence_io_sun_glint', 'confidence_io_snow',
                                    'confidence_io_summary_cloud', 'confidence_io_summary_pointing',
                                    'pointing_io_FlipMirrorAbsoluteError', 'pointing_io_FlipMirrorIntegratedError',
                                    'pointing_io_FlipMirrorRMSError', 'pointing_io_ScanMirrorAbsoluteError',
                                    'pointing_io_ScanMirrorIntegratedError', 'pointing_io_ScanMirrorRMSError',
                                    'pointing_io_ScanTimeError', 'pointing_io_Platform_Mode',
                                    'S7_exception_in_ISP_absent', 'S7_exception_in_pixel_absent',
                                    'S7_exception_in_not_decompressed', 'S7_exception_in_no_signal',
                                    'S7_exception_in_saturation', 'S7_exception_in_invalid_radiance',
                                    'S7_exception_in_no_parameters', 'S7_exception_in_unfilled_pixel',
                                    'S7_exception_io_ISP_absent', 'S7_exception_io_pixel_absent',
                                    'S7_exception_io_not_decompressed', 'S7_exception_io_no_signal',
                                    'S7_exception_io_saturation', 'S7_exception_io_invalid_radiance',
                                    'S7_exception_io_no_parameters', 'S7_exception_io_unfilled_pixel',
                                    'S8_exception_in_ISP_absent', 'S8_exception_in_pixel_absent',
                                    'S8_exception_in_not_decompressed', 'S8_exception_in_no_signal',
                                    'S8_exception_in_saturation', 'S8_exception_in_invalid_radiance',
                                    'S8_exception_in_no_parameters', 'S8_exception_in_unfilled_pixel',
                                    'S8_exception_io_ISP_absent', 'S8_exception_io_pixel_absent',
                                    'S8_exception_io_not_decompressed', 'S8_exception_io_no_signal',
                                    'S8_exception_io_saturation', 'S8_exception_io_invalid_radiance',
                                    'S8_exception_io_no_parameters', 'S8_exception_io_unfilled_pixel',
                                    'S9_exception_in_ISP_absent', 'S9_exception_in_pixel_absent',
                                    'S9_exception_in_not_decompressed', 'S9_exception_in_no_signal',
                                    'S9_exception_in_saturation', 'S9_exception_in_invalid_radiance',
                                    'S9_exception_in_no_parameters', 'S9_exception_in_unfilled_pixel',
                                    'S9_exception_io_ISP_absent', 'S9_exception_io_pixel_absent',
                                    'S9_exception_io_not_decompressed', 'S9_exception_io_no_signal',
                                    'S9_exception_io_saturation', 'S9_exception_io_invalid_radiance',
                                    'S9_exception_io_no_parameters', 'S9_exception_io_unfilled_pixel']


expected_mask_variable_names_500m = ['F1_exception_in_ISP_absent', 'F1_exception_in_pixel_absent',
                                     'F1_exception_in_not_decompressed', 'F1_exception_in_no_signal',
                                     'F1_exception_in_saturation', 'F1_exception_in_invalid_radiance',
                                     'F1_exception_in_no_parameters', 'F1_exception_in_unfilled_pixel',
                                     'F1_exception_io_ISP_absent', 'F1_exception_io_pixel_absent',
                                     'F1_exception_io_not_decompressed', 'F1_exception_io_no_signal',
                                     'F1_exception_io_saturation', 'F1_exception_io_invalid_radiance',
                                     'F1_exception_io_no_parameters', 'F1_exception_io_unfilled_pixel',
                                     'F2_exception_in_ISP_absent', 'F2_exception_in_pixel_absent',
                                     'F2_exception_in_not_decompressed', 'F2_exception_in_no_signal',
                                     'F2_exception_in_saturation', 'F2_exception_in_invalid_radiance',
                                     'F2_exception_in_no_parameters', 'F2_exception_in_unfilled_pixel',
                                     'F2_exception_io_ISP_absent', 'F2_exception_io_pixel_absent',
                                     'F2_exception_io_not_decompressed', 'F2_exception_io_no_signal',
                                     'F2_exception_io_saturation', 'F2_exception_io_invalid_radiance',
                                     'F2_exception_io_no_parameters', 'F2_exception_io_unfilled_pixel',
                                     'bayes_an_single_low', 'bayes_an_single_moderate', 'bayes_an_dual_low',
                                     'bayes_an_dual_moderate', 'cloud_an_visible', 'cloud_an_1_37_threshold',
                                     'cloud_an_1_6_small_histogram', 'cloud_an_1_6_large_histogram',
                                     'cloud_an_2_25_small_histogram', 'cloud_an_2_25_large_histogram',
                                     'cloud_an_11_spatial_coherence', 'cloud_an_gross_cloud', 'cloud_an_thin_cirrus',
                                     'cloud_an_medium_high', 'cloud_an_fog_low_stratus',
                                     'cloud_an_11_12_view_difference', 'cloud_an_3_7_11_view_difference',
                                     'cloud_an_thermal_histogram', 'confidence_an_coastline', 'confidence_an_ocean',
                                     'confidence_an_tidal', 'confidence_an_land', 'confidence_an_inland_water',
                                     'confidence_an_unfilled', 'confidence_an_cosmetic', 'confidence_an_duplicate',
                                     'confidence_an_day', 'confidence_an_twilight', 'confidence_an_sun_glint',
                                     'confidence_an_snow', 'confidence_an_summary_cloud',
                                     'confidence_an_summary_pointing', 'pointing_an_FlipMirrorAbsoluteError',
                                     'pointing_an_FlipMirrorIntegratedError', 'pointing_an_FlipMirrorRMSError',
                                     'pointing_an_ScanMirrorAbsoluteError', 'pointing_an_ScanMirrorIntegratedError',
                                     'pointing_an_ScanMirrorRMSError', 'pointing_an_ScanTimeError',
                                     'pointing_an_Platform_Mode', 'bayes_ao_single_low', 'bayes_ao_single_moderate',
                                     'bayes_ao_dual_low', 'bayes_ao_dual_moderate', 'cloud_ao_visible',
                                     'cloud_ao_1_37_threshold', 'cloud_ao_1_6_small_histogram',
                                     'cloud_ao_1_6_large_histogram', 'cloud_ao_2_25_small_histogram',
                                     'cloud_ao_2_25_large_histogram', 'cloud_ao_11_spatial_coherence',
                                     'cloud_ao_gross_cloud', 'cloud_ao_thin_cirrus', 'cloud_ao_medium_high',
                                     'cloud_ao_fog_low_stratus', 'cloud_ao_11_12_view_difference',
                                     'cloud_ao_3_7_11_view_difference', 'cloud_ao_thermal_histogram',
                                     'confidence_ao_coastline', 'confidence_ao_ocean', 'confidence_ao_tidal',
                                     'confidence_ao_land', 'confidence_ao_inland_water', 'confidence_ao_unfilled',
                                     'confidence_ao_cosmetic', 'confidence_ao_duplicate', 'confidence_ao_day',
                                     'confidence_ao_twilight', 'confidence_ao_sun_glint', 'confidence_ao_snow',
                                     'confidence_ao_summary_cloud', 'confidence_ao_summary_pointing',
                                     'pointing_ao_FlipMirrorAbsoluteError', 'pointing_ao_FlipMirrorIntegratedError',
                                     'pointing_ao_FlipMirrorRMSError', 'pointing_ao_ScanMirrorAbsoluteError',
                                     'pointing_ao_ScanMirrorIntegratedError', 'pointing_ao_ScanMirrorRMSError',
                                     'pointing_ao_ScanTimeError', 'pointing_ao_Platform_Mode', 'bayes_bn_single_low',
                                     'bayes_bn_single_moderate', 'bayes_bn_dual_low', 'bayes_bn_dual_moderate',
                                     'cloud_bn_visible', 'cloud_bn_1_37_threshold', 'cloud_bn_1_6_small_histogram',
                                     'cloud_bn_1_6_large_histogram', 'cloud_bn_2_25_small_histogram',
                                     'cloud_bn_2_25_large_histogram', 'cloud_bn_11_spatial_coherence',
                                     'cloud_bn_gross_cloud', 'cloud_bn_thin_cirrus', 'cloud_bn_medium_high',
                                     'cloud_bn_fog_low_stratus', 'cloud_bn_11_12_view_difference',
                                     'cloud_bn_3_7_11_view_difference', 'cloud_bn_thermal_histogram',
                                     'confidence_bn_coastline', 'confidence_bn_ocean', 'confidence_bn_tidal',
                                     'confidence_bn_land', 'confidence_bn_inland_water', 'confidence_bn_unfilled',
                                     'confidence_bn_cosmetic', 'confidence_bn_duplicate', 'confidence_bn_day',
                                     'confidence_bn_twilight', 'confidence_bn_sun_glint', 'confidence_bn_snow',
                                     'confidence_bn_summary_cloud', 'confidence_bn_summary_pointing',
                                     'pointing_bn_FlipMirrorAbsoluteError', 'pointing_bn_FlipMirrorIntegratedError',
                                     'pointing_bn_FlipMirrorRMSError', 'pointing_bn_ScanMirrorAbsoluteError',
                                     'pointing_bn_ScanMirrorIntegratedError', 'pointing_bn_ScanMirrorRMSError',
                                     'pointing_bn_ScanTimeError', 'pointing_bn_Platform_Mode', 'bayes_bo_single_low',
                                     'bayes_bo_single_moderate', 'bayes_bo_dual_low', 'bayes_bo_dual_moderate',
                                     'cloud_bo_visible', 'cloud_bo_1_37_threshold', 'cloud_bo_1_6_small_histogram',
                                     'cloud_bo_1_6_large_histogram', 'cloud_bo_2_25_small_histogram',
                                     'cloud_bo_2_25_large_histogram', 'cloud_bo_11_spatial_coherence',
                                     'cloud_bo_gross_cloud', 'cloud_bo_thin_cirrus', 'cloud_bo_medium_high',
                                     'cloud_bo_fog_low_stratus', 'cloud_bo_11_12_view_difference',
                                     'cloud_bo_3_7_11_view_difference', 'cloud_bo_thermal_histogram',
                                     'confidence_bo_coastline', 'confidence_bo_ocean', 'confidence_bo_tidal',
                                     'confidence_bo_land', 'confidence_bo_inland_water', 'confidence_bo_unfilled',
                                     'confidence_bo_cosmetic', 'confidence_bo_duplicate', 'confidence_bo_day',
                                     'confidence_bo_twilight', 'confidence_bo_sun_glint', 'confidence_bo_snow',
                                     'confidence_bo_summary_cloud', 'confidence_bo_summary_pointing',
                                     'pointing_bo_FlipMirrorAbsoluteError', 'pointing_bo_FlipMirrorIntegratedError',
                                     'pointing_bo_FlipMirrorRMSError', 'pointing_bo_ScanMirrorAbsoluteError',
                                     'pointing_bo_ScanMirrorIntegratedError', 'pointing_bo_ScanMirrorRMSError',
                                     'pointing_bo_ScanTimeError', 'pointing_bo_Platform_Mode', 'bayes_cn_single_low',
                                     'bayes_cn_single_moderate', 'bayes_cn_dual_low', 'bayes_cn_dual_moderate',
                                     'cloud_cn_visible', 'cloud_cn_1_37_threshold', 'cloud_cn_1_6_small_histogram',
                                     'cloud_cn_1_6_large_histogram', 'cloud_cn_2_25_small_histogram',
                                     'cloud_cn_2_25_large_histogram', 'cloud_cn_11_spatial_coherence',
                                     'cloud_cn_gross_cloud', 'cloud_cn_thin_cirrus', 'cloud_cn_medium_high',
                                     'cloud_cn_fog_low_stratus', 'cloud_cn_11_12_view_difference',
                                     'cloud_cn_3_7_11_view_difference', 'cloud_cn_thermal_histogram',
                                     'confidence_cn_coastline', 'confidence_cn_ocean', 'confidence_cn_tidal',
                                     'confidence_cn_land', 'confidence_cn_inland_water', 'confidence_cn_unfilled',
                                     'confidence_cn_cosmetic', 'confidence_cn_duplicate', 'confidence_cn_day',
                                     'confidence_cn_twilight', 'confidence_cn_sun_glint', 'confidence_cn_snow',
                                     'confidence_cn_summary_cloud', 'confidence_cn_summary_pointing',
                                     'pointing_cn_FlipMirrorAbsoluteError', 'pointing_cn_FlipMirrorIntegratedError',
                                     'pointing_cn_FlipMirrorRMSError', 'pointing_cn_ScanMirrorAbsoluteError',
                                     'pointing_cn_ScanMirrorIntegratedError', 'pointing_cn_ScanMirrorRMSError',
                                     'pointing_cn_ScanTimeError', 'pointing_cn_Platform_Mode', 'bayes_co_single_low',
                                     'bayes_co_single_moderate', 'bayes_co_dual_low', 'bayes_co_dual_moderate',
                                     'cloud_co_visible', 'cloud_co_1_37_threshold', 'cloud_co_1_6_small_histogram',
                                     'cloud_co_1_6_large_histogram', 'cloud_co_2_25_small_histogram',
                                     'cloud_co_2_25_large_histogram', 'cloud_co_11_spatial_coherence',
                                     'cloud_co_gross_cloud', 'cloud_co_thin_cirrus', 'cloud_co_medium_high',
                                     'cloud_co_fog_low_stratus', 'cloud_co_11_12_view_difference',
                                     'cloud_co_3_7_11_view_difference', 'cloud_co_thermal_histogram',
                                     'confidence_co_coastline', 'confidence_co_ocean', 'confidence_co_tidal',
                                     'confidence_co_land', 'confidence_co_inland_water', 'confidence_co_unfilled',
                                     'confidence_co_cosmetic', 'confidence_co_duplicate', 'confidence_co_day',
                                     'confidence_co_twilight', 'confidence_co_sun_glint', 'confidence_co_snow',
                                     'confidence_co_summary_cloud', 'confidence_co_summary_pointing',
                                     'pointing_co_FlipMirrorAbsoluteError', 'pointing_co_FlipMirrorIntegratedError',
                                     'pointing_co_FlipMirrorRMSError', 'pointing_co_ScanMirrorAbsoluteError',
                                     'pointing_co_ScanMirrorIntegratedError', 'pointing_co_ScanMirrorRMSError',
                                     'pointing_co_ScanTimeError', 'pointing_co_Platform_Mode', 'bayes_in_single_low',
                                     'bayes_in_single_moderate', 'bayes_in_dual_low', 'bayes_in_dual_moderate',
                                     'cloud_in_visible', 'cloud_in_1_37_threshold', 'cloud_in_1_6_small_histogram',
                                     'cloud_in_1_6_large_histogram', 'cloud_in_2_25_small_histogram',
                                     'cloud_in_2_25_large_histogram', 'cloud_in_11_spatial_coherence',
                                     'cloud_in_gross_cloud', 'cloud_in_thin_cirrus', 'cloud_in_medium_high',
                                     'cloud_in_fog_low_stratus', 'cloud_in_11_12_view_difference',
                                     'cloud_in_3_7_11_view_difference', 'cloud_in_thermal_histogram',
                                     'confidence_in_coastline', 'confidence_in_ocean', 'confidence_in_tidal',
                                     'confidence_in_land', 'confidence_in_inland_water', 'confidence_in_unfilled',
                                     'confidence_in_cosmetic', 'confidence_in_duplicate', 'confidence_in_day',
                                     'confidence_in_twilight', 'confidence_in_sun_glint', 'confidence_in_snow',
                                     'confidence_in_summary_cloud', 'confidence_in_summary_pointing',
                                     'pointing_in_FlipMirrorAbsoluteError', 'pointing_in_FlipMirrorIntegratedError',
                                     'pointing_in_FlipMirrorRMSError', 'pointing_in_ScanMirrorAbsoluteError',
                                     'pointing_in_ScanMirrorIntegratedError', 'pointing_in_ScanMirrorRMSError',
                                     'pointing_in_ScanTimeError', 'pointing_in_Platform_Mode', 'bayes_io_single_low',
                                     'bayes_io_single_moderate', 'bayes_io_dual_low', 'bayes_io_dual_moderate',
                                     'cloud_io_visible', 'cloud_io_1_37_threshold', 'cloud_io_1_6_small_histogram',
                                     'cloud_io_1_6_large_histogram', 'cloud_io_2_25_small_histogram',
                                     'cloud_io_2_25_large_histogram', 'cloud_io_11_spatial_coherence',
                                     'cloud_io_gross_cloud', 'cloud_io_thin_cirrus', 'cloud_io_medium_high',
                                     'cloud_io_fog_low_stratus', 'cloud_io_11_12_view_difference',
                                     'cloud_io_3_7_11_view_difference', 'cloud_io_thermal_histogram',
                                     'confidence_io_coastline', 'confidence_io_ocean', 'confidence_io_tidal',
                                     'confidence_io_land', 'confidence_io_inland_water', 'confidence_io_unfilled',
                                     'confidence_io_cosmetic', 'confidence_io_duplicate', 'confidence_io_day',
                                     'confidence_io_twilight', 'confidence_io_sun_glint', 'confidence_io_snow',
                                     'confidence_io_summary_cloud', 'confidence_io_summary_pointing',
                                     'pointing_io_FlipMirrorAbsoluteError', 'pointing_io_FlipMirrorIntegratedError',
                                     'pointing_io_FlipMirrorRMSError', 'pointing_io_ScanMirrorAbsoluteError',
                                     'pointing_io_ScanMirrorIntegratedError', 'pointing_io_ScanMirrorRMSError',
                                     'pointing_io_ScanTimeError', 'pointing_io_Platform_Mode',
                                     'S1_exception_an_ISP_absent', 'S1_exception_an_pixel_absent',
                                     'S1_exception_an_not_decompressed', 'S1_exception_an_no_signal',
                                     'S1_exception_an_saturation', 'S1_exception_an_invalid_radiance',
                                     'S1_exception_an_no_parameters', 'S1_exception_an_unfilled_pixel',
                                     'S1_exception_ao_ISP_absent', 'S1_exception_ao_pixel_absent',
                                     'S1_exception_ao_not_decompressed', 'S1_exception_ao_no_signal',
                                     'S1_exception_ao_saturation', 'S1_exception_ao_invalid_radiance',
                                     'S1_exception_ao_no_parameters', 'S1_exception_ao_unfilled_pixel',
                                     'S2_exception_an_ISP_absent', 'S2_exception_an_pixel_absent',
                                     'S2_exception_an_not_decompressed', 'S2_exception_an_no_signal',
                                     'S2_exception_an_saturation', 'S2_exception_an_invalid_radiance',
                                     'S2_exception_an_no_parameters', 'S2_exception_an_unfilled_pixel',
                                     'S2_exception_ao_ISP_absent', 'S2_exception_ao_pixel_absent',
                                     'S2_exception_ao_not_decompressed', 'S2_exception_ao_no_signal',
                                     'S2_exception_ao_saturation', 'S2_exception_ao_invalid_radiance',
                                     'S2_exception_ao_no_parameters', 'S2_exception_ao_unfilled_pixel',
                                     'S3_exception_an_ISP_absent', 'S3_exception_an_pixel_absent',
                                     'S3_exception_an_not_decompressed', 'S3_exception_an_no_signal',
                                     'S3_exception_an_saturation', 'S3_exception_an_invalid_radiance',
                                     'S3_exception_an_no_parameters', 'S3_exception_an_unfilled_pixel',
                                     'S3_exception_ao_ISP_absent', 'S3_exception_ao_pixel_absent',
                                     'S3_exception_ao_not_decompressed', 'S3_exception_ao_no_signal',
                                     'S3_exception_ao_saturation', 'S3_exception_ao_invalid_radiance',
                                     'S3_exception_ao_no_parameters', 'S3_exception_ao_unfilled_pixel',
                                     'S4_exception_an_ISP_absent', 'S4_exception_an_pixel_absent',
                                     'S4_exception_an_not_decompressed', 'S4_exception_an_no_signal',
                                     'S4_exception_an_saturation', 'S4_exception_an_invalid_radiance',
                                     'S4_exception_an_no_parameters', 'S4_exception_an_unfilled_pixel',
                                     'S4_exception_ao_ISP_absent', 'S4_exception_ao_pixel_absent',
                                     'S4_exception_ao_not_decompressed', 'S4_exception_ao_no_signal',
                                     'S4_exception_ao_saturation', 'S4_exception_ao_invalid_radiance',
                                     'S4_exception_ao_no_parameters', 'S4_exception_ao_unfilled_pixel',
                                     'S4_exception_bn_ISP_absent', 'S4_exception_bn_pixel_absent',
                                     'S4_exception_bn_not_decompressed', 'S4_exception_bn_no_signal',
                                     'S4_exception_bn_saturation', 'S4_exception_bn_invalid_radiance',
                                     'S4_exception_bn_no_parameters', 'S4_exception_bn_unfilled_pixel',
                                     'S4_exception_bo_ISP_absent', 'S4_exception_bo_pixel_absent',
                                     'S4_exception_bo_not_decompressed', 'S4_exception_bo_no_signal',
                                     'S4_exception_bo_saturation', 'S4_exception_bo_invalid_radiance',
                                     'S4_exception_bo_no_parameters', 'S4_exception_bo_unfilled_pixel',
                                     'S4_exception_cn_ISP_absent', 'S4_exception_cn_pixel_absent',
                                     'S4_exception_cn_not_decompressed', 'S4_exception_cn_no_signal',
                                     'S4_exception_cn_saturation', 'S4_exception_cn_invalid_radiance',
                                     'S4_exception_cn_no_parameters', 'S4_exception_cn_unfilled_pixel',
                                     'S4_exception_co_ISP_absent', 'S4_exception_co_pixel_absent',
                                     'S4_exception_co_not_decompressed', 'S4_exception_co_no_signal',
                                     'S4_exception_co_saturation', 'S4_exception_co_invalid_radiance',
                                     'S4_exception_co_no_parameters', 'S4_exception_co_unfilled_pixel',
                                     'S5_exception_an_ISP_absent', 'S5_exception_an_pixel_absent',
                                     'S5_exception_an_not_decompressed', 'S5_exception_an_no_signal',
                                     'S5_exception_an_saturation', 'S5_exception_an_invalid_radiance',
                                     'S5_exception_an_no_parameters', 'S5_exception_an_unfilled_pixel',
                                     'S5_exception_ao_ISP_absent', 'S5_exception_ao_pixel_absent',
                                     'S5_exception_ao_not_decompressed', 'S5_exception_ao_no_signal',
                                     'S5_exception_ao_saturation', 'S5_exception_ao_invalid_radiance',
                                     'S5_exception_ao_no_parameters', 'S5_exception_ao_unfilled_pixel',
                                     'S5_exception_bn_ISP_absent', 'S5_exception_bn_pixel_absent',
                                     'S5_exception_bn_not_decompressed', 'S5_exception_bn_no_signal',
                                     'S5_exception_bn_saturation', 'S5_exception_bn_invalid_radiance',
                                     'S5_exception_bn_no_parameters', 'S5_exception_bn_unfilled_pixel',
                                     'S5_exception_bo_ISP_absent', 'S5_exception_bo_pixel_absent',
                                     'S5_exception_bo_not_decompressed', 'S5_exception_bo_no_signal',
                                     'S5_exception_bo_saturation', 'S5_exception_bo_invalid_radiance',
                                     'S5_exception_bo_no_parameters', 'S5_exception_bo_unfilled_pixel',
                                     'S5_exception_cn_ISP_absent', 'S5_exception_cn_pixel_absent',
                                     'S5_exception_cn_not_decompressed', 'S5_exception_cn_no_signal',
                                     'S5_exception_cn_saturation', 'S5_exception_cn_invalid_radiance',
                                     'S5_exception_cn_no_parameters', 'S5_exception_cn_unfilled_pixel',
                                     'S5_exception_co_ISP_absent', 'S5_exception_co_pixel_absent',
                                     'S5_exception_co_not_decompressed', 'S5_exception_co_no_signal',
                                     'S5_exception_co_saturation', 'S5_exception_co_invalid_radiance',
                                     'S5_exception_co_no_parameters', 'S5_exception_co_unfilled_pixel',
                                     'S6_exception_an_ISP_absent', 'S6_exception_an_pixel_absent',
                                     'S6_exception_an_not_decompressed', 'S6_exception_an_no_signal',
                                     'S6_exception_an_saturation', 'S6_exception_an_invalid_radiance',
                                     'S6_exception_an_no_parameters', 'S6_exception_an_unfilled_pixel',
                                     'S6_exception_ao_ISP_absent', 'S6_exception_ao_pixel_absent',
                                     'S6_exception_ao_not_decompressed', 'S6_exception_ao_no_signal',
                                     'S6_exception_ao_saturation', 'S6_exception_ao_invalid_radiance',
                                     'S6_exception_ao_no_parameters', 'S6_exception_ao_unfilled_pixel',
                                     'S6_exception_bn_ISP_absent', 'S6_exception_bn_pixel_absent',
                                     'S6_exception_bn_not_decompressed', 'S6_exception_bn_no_signal',
                                     'S6_exception_bn_saturation', 'S6_exception_bn_invalid_radiance',
                                     'S6_exception_bn_no_parameters', 'S6_exception_bn_unfilled_pixel',
                                     'S6_exception_bo_ISP_absent', 'S6_exception_bo_pixel_absent',
                                     'S6_exception_bo_not_decompressed', 'S6_exception_bo_no_signal',
                                     'S6_exception_bo_saturation', 'S6_exception_bo_invalid_radiance',
                                     'S6_exception_bo_no_parameters', 'S6_exception_bo_unfilled_pixel',
                                     'S6_exception_cn_ISP_absent', 'S6_exception_cn_pixel_absent',
                                     'S6_exception_cn_not_decompressed', 'S6_exception_cn_no_signal',
                                     'S6_exception_cn_saturation', 'S6_exception_cn_invalid_radiance',
                                     'S6_exception_cn_no_parameters', 'S6_exception_cn_unfilled_pixel',
                                     'S6_exception_co_ISP_absent', 'S6_exception_co_pixel_absent',
                                     'S6_exception_co_not_decompressed', 'S6_exception_co_no_signal',
                                     'S6_exception_co_saturation', 'S6_exception_co_invalid_radiance',
                                     'S6_exception_co_no_parameters', 'S6_exception_co_unfilled_pixel',
                                     'S7_exception_in_ISP_absent', 'S7_exception_in_pixel_absent',
                                     'S7_exception_in_not_decompressed', 'S7_exception_in_no_signal',
                                     'S7_exception_in_saturation', 'S7_exception_in_invalid_radiance',
                                     'S7_exception_in_no_parameters', 'S7_exception_in_unfilled_pixel',
                                     'S7_exception_io_ISP_absent', 'S7_exception_io_pixel_absent',
                                     'S7_exception_io_not_decompressed', 'S7_exception_io_no_signal',
                                     'S7_exception_io_saturation', 'S7_exception_io_invalid_radiance',
                                     'S7_exception_io_no_parameters', 'S7_exception_io_unfilled_pixel',
                                     'S8_exception_in_ISP_absent', 'S8_exception_in_pixel_absent',
                                     'S8_exception_in_not_decompressed', 'S8_exception_in_no_signal',
                                     'S8_exception_in_saturation', 'S8_exception_in_invalid_radiance',
                                     'S8_exception_in_no_parameters', 'S8_exception_in_unfilled_pixel',
                                     'S8_exception_io_ISP_absent', 'S8_exception_io_pixel_absent',
                                     'S8_exception_io_not_decompressed', 'S8_exception_io_no_signal',
                                     'S8_exception_io_saturation', 'S8_exception_io_invalid_radiance',
                                     'S8_exception_io_no_parameters', 'S8_exception_io_unfilled_pixel',
                                     'S9_exception_in_ISP_absent', 'S9_exception_in_pixel_absent',
                                     'S9_exception_in_not_decompressed', 'S9_exception_in_no_signal',
                                     'S9_exception_in_saturation', 'S9_exception_in_invalid_radiance',
                                     'S9_exception_in_no_parameters', 'S9_exception_in_unfilled_pixel',
                                     'S9_exception_io_ISP_absent', 'S9_exception_io_pixel_absent',
                                     'S9_exception_io_not_decompressed', 'S9_exception_io_no_signal',
                                     'S9_exception_io_saturation', 'S9_exception_io_invalid_radiance',
                                     'S9_exception_io_no_parameters', 'S9_exception_io_unfilled_pixel']


if __name__ == "__main__":
    diff = [n for n in expected_mask_variable_names_1km if n in expected_mask_variable_names_500m]
    for i, d in enumerate(diff):
        print i, d
